# Generated by Django 5.2.4 on 2025-07-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sauces', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pizza',
            },
        ),
    ]
